### ISSUE TITLE
Issue to increase interaction in GitHub.

### ISSUE THREAD

**Issue by Lazeeez** [Lazeeez/HacktoberFest-21#17]
Github majorly revolves around the interactivity of the repository (stars and forks and commits, etc.). comment here if you wanna exchange stars and forks to increase interactivity.

**Comment by RoyalTechie** [comment]
Done

**Comment by meks-0202** [comment]
interested in what?

**Comment by meks-0202** [comment]
Yeah sure.

**Comment by Lazeeez** [comment]
@RoyalTechie @AnAi05 and @meks-0202 make sure you all follow each other and try to expand this as more as possible to your friends, colleagues, peers, co-workers... the more people the better

**Comment by Lazeeez** [comment]
@salonishukla206 are you interested?
